theme = "hyde-x"

baseurl = "http://ConscientiousProgrammer.com"
languageCode = "en-us"
title = "The Conscientious Programmer"
pygmentsstyle = "default"
paginate = 10
disqusShortname = "conscientiousprogrammer"
RssUri = "atom.xml"
RelativeURLs = "true"
MetaDataFormat = "yaml"

[author]
name = "Franklin Chen"

[permalinks]
post = "/blog/:year/:month/:day/:title/"

[taxonomies]
category = "categories"

[params]
truncate = true
defaultDescription = "Franklin Chen's thoughts about computer programming"
defaultKeywords = "Franklin Chen, programming, blog"

#gravatarHash = "f8a7ccb41af2422d10599464b96cf034"

theme = "theme-base-0e"

highlight = "default"
tagline = "Humbly exploring what it means to do the right thing."
home = "The Conscientious Programmer"

googleAuthorship = "100967806642012078047"
googleAnalytics = "UA-41982602-1"

github = "https://github.com/FranklinChen"
#bitbucket = "https://bitbucket.org/FranklinChen/"
stackOverflow = ""
linkedin = "http://www.linkedin.com/in/franklinchen"
googleplus = "http://google.com/+FranklinChen"
facebook = "http://www.facebook.com/franklin.chen"
twitter = "http://twitter.com/franklinchen"
youtube = "http://www.youtube.com/user/FranklinChen"
rss = true
flatter = ""
